### ISSUE TITLE
Problem running pipeline

### ISSUE THREAD

**Issue by bheimbu** [ThiloSchulze/mitogenome-extraction#3]
Dear Thilo,

I'd like to use your pipeline but I cannot make it to run. I'm actually at the same University as you, sitting in the lower floor (AG Scheu, Animal Ecology). What I did so far is to download the repo and I've loaded following modules on the HPC of the GWDG: `anaconda3` and `openjdk` in order to fullfill the requirements (JAVA and anaconda).
However, I receive following [error message](https://github.com/ThiloSchulze/mitogenome-extraction/files/10012545/error_message.txt).

Any help  is highly appreciated,

Bastian

**Comment by ThiloSchulze** [comment]
Dear Bastian,
Are you available this week? I could visit your office and we can take a look at it together.

Kind regards,
Thilo

**Comment by bheimbu** [comment]
Hi,

I'm here. First floor, room 303.

See you soon,

Bastian

**Comment by ThiloSchulze** [comment]
I'll be there in roughly 30 minutes.

**Comment by bheimbu** [comment]
Hi, bist du noch da? Es läuft nicht...

**Comment by bheimbu** [comment]
Hi,

habt den Lauf abgebrochen und dir eine Email unter thilo.schulze@biologie.uni-goettingen.de zukommen lassen mit allen nötigen Links zum Download der Dateien (owncloud upload hat auch schon wieder nicht funktioniert).

Bastian

**Comment by ThiloSchulze** [comment]
Hi,
Die Pipeline lief wie vorgesehen für deine Daten. Das fehlende conda environment könnte das Problem bei deinem Versuch gewesen sein. Ich kann dir das annotierte Mitochondrium vorbeibringen, wenn du heute noch hier bist.

Viele Grüße,
Thilo

**Comment by bheimbu** [comment]
Hi,

bin nur noch für 20 min da, kannst du es mir per Email schicken?


Und wie soll ich dann weiter vorgehen? Kannst du mir vll mal schicken, welche Programme du installiert hast (d.h. welche Version Anaconda etc.), damit ich es lokal bei mir laufen kann, wenn es schon nicht auf dem Cluster läuft?!


Grüße,

Bastian
